val scala3Version = "3.2.2"

lazy val root = project
  .in(file("."))
  .settings(
    name := "organizer",
    version := "0.1.0-SNAPSHOT",

    scalaVersion := scala3Version,

    // autogenerated from sbt
    libraryDependencies += "org.scalameta" %% "munit" % "0.7.29" % Test,

    // added based on Piconot external DSL dependencies
    libraryDependencies += "org.scalatest" %% "scalatest" % "3.2.9" % Test,
    libraryDependencies += "org.scalacheck" %% "scalacheck" % "1.15.4" % Test,
    libraryDependencies += "org.scala-lang.modules" %% "scala-parser-combinators" % "2.2.0",
    libraryDependencies += "org.scala-lang" %% "scala3-compiler" % scalaVersion.value,

    // microsoft word dependency
    libraryDependencies += "org.apache.poi" % "poi" % "5.2.3",
    libraryDependencies += "org.apache.poi" % "poi-ooxml" % "5.2.3",
    libraryDependencies += "org.apache.poi" % "poi-ooxml-lite" % "5.2.3",
  )
